// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzfeghfpydtvzibsjvkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56ZmVnaGZweWR0dnppYnNqdmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2MzY4MjksImV4cCI6MjA4NzIxMjgyOX0.r7Wxe3m8tAXGngQ_DdFzoSOyXgWMqqBQyShpB103gNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});